config/routes.rb
Rails.application.routes.draw do
  resources :guests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: %i[ show edit update destroy ]

  # GET /guests or /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1 or /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests or /guests.json
  def create
    @guest = Guest.new(guest_params)
    if @guest.save
    redirect_to @guest
    else
    end

    # respond_to do |format|
    #   if @guest.save
    #     redirect_to @guest
    #     # format.html { redirect_to @guest, notice: "Guest was successfully created.",allow_other_host: true }
    #     # format.json { render :show, status: :created, location: @guest }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @guest.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /guests/1 or /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to guest_url(@guest), notice: "Guest was successfully updated." }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1 or /guests/1.json
  def destroy
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url, notice: "Guest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guest_params
      params.require(:guest).permit(:name, :attending, :people)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest) do |form| %>
  <% if guest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
        <% guest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :attending, style: "display: block" %>
    <%= form.check_box :attending %>
  </div>

  <div>
    <%= form.label :people, style: "display: block" %>
    <%= form.number_field :people %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/guests/_guest.html.erb
<div id="<%= dom_id guest %>">
  <p>
    <strong>Name:</strong>
    <%= guest.name %>
  </p>

  <p>
    <strong>Attending:</strong>
    <%= guest.attending %>
  </p>

  <p>
    <strong>People:</strong>
    <%= guest.people %>
  </p>

</div>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render "form", guest: @guest %>

<br>

<div>
  <%= link_to "Show this guest", @guest %> |
  <%= link_to "Back to guests", guests_path %>
</div>

app/views/guests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Guests</h1>

<div id="guests">
  <% @guests.each do |guest| %>
    <%= render guest %>
    ===========================================
    <p>
      <%# <%= link_to "Show this guest", guest %>
    </p>
  <% end %>
</div>

<%# <%= link_to "New guest", new_guest_path %> 

app/views/guests/new.html.erb
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Satisfy&family=Send+Flowers&family=Bitter&display=swap"
      rel="stylesheet"
    />
    <style>
      body {
        animation: fadein 2.5s ease-in;
        background-color: #ecd;
        font-family: Send Flowers;
        text-align: center;
        margin: 0px;
      }

      @keyframes fadein {
        0% {
          opacity: 0;
        }

        100% {
          opacity: 1;
        }
      }
      h1 {
        font-size: 4em;
        margin-top: 0px;
        margin-bottom: 0.25em;
        margin-top: -20px;
        text-shadow: 0 0 10px #fff, 0 0 10px #fff, 0 0 10px #fff, 0 0 10px #fff,
          0 0 10px #fff, 0 0 10px #fff, 0 0 10px #fff, 0 0 10px #fff;
      }

      h2 {
        font-family: Send Flowers;
        font-size: 3em;
        margin-top: 0;
        margin-bottom: 0.25em;
      }

      h3 {
        font-family: Send Flowers;
        font-size: 2.5em;
        margin-top: 0;
        margin-bottom: 0.5em;
      }

      #dice-image {
        height: 150px;
        width: auto;
      }

      .smallrose {
        height: 100px;
        width: auto;
      }

      .checkbox {
        border: 6px solid black;
        color: #c00;
        height: 75px;
        width: 75px;
        font-size: 60px;
        margin: 0px 50px;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      .checkbox-wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
      }

      #checkbox-container {
        display: flex;
        justify-content: center;
        width: 80%;
      }

      #nameinput {
        background: none;
        border: none;
        border-top: 1px solid #ecd;
        border-left: 1px solid #ecd;
        border-right: 1px solid #ecd;
        border-bottom: 5px solid black;
        color: #c00;
        font-family: Satisfy;
        font-size: 2.5em;
        font-weight: 200;
        padding: 0px;
        text-align: center;
        width: 80%;
      }

      #nameinput:focus {
        outline: none;
      }

      #nameinput-label {
        font-size: 2em;
        font-weight: 700;
      }

      #guest-selector {
        background: none;
        border: 0;
        color: #c00;
        font-size: 2.5em;
        font-family: Send Flowers;
        font-weight: 700;
        margin-left: 20px;
        width: 44px;
      }
      #guest-selector:focus {
        outline: none;
      }
      #guestcount-container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px;
      }

      #submit {
        border: 5px solid black;
        background-color: transparent;
        color: #000;
        display: block;
        font-family: Bitter;
        font-size: 2em;
        font-weight: 700;
        letter-spacing: 2px;
        margin-top: 25px;
        padding: 10px 30px;
        transition: background-color 0.3s ease-in, color 0.3s ease-in;
      }
    </style>
  </head>
  <body>
    <%= image_tag ("dice.png"), id: "dice-image" %>
    <div style="display: flex; justify-content: center">
      <h1>Are you in?</h1>
    </div>
    <%= form_with scope: :guest, url: guests_path, local:true do |f| %>
    <input
      type="checkbox"
      id="attending"
      name="guest[attending]"
      style="display: none"
      value="true"
    />
    <div style="display: flex; justify-content: center">
      <div id="checkbox-container">
        <div class="checkbox-wrapper">
          <div
            class="checkbox"
            id="yescheckbox"
            onclick="selectAttending('yes')"
          ></div>
          <h2>Yes</h2>
        </div>
        <div class="checkbox-wrapper">
          <div
            class="checkbox"
            id="nocheckbox"
            onclick="selectAttending('no')"
          ></div>
          <h2>No</h2>
        </div>
      </div>
    </div>
    <input
      id="nameinput"
      name="guest[name]"
      required
      onchange="hideMultiGuest()"
    /><br />
    <label for="nameinput" id="nameinput-label">Your Name</label>
    <div id="guestcount-container">
      <h3 style="margin-bottom: 0">Attending:</h3>
      <div>
        <select id="guest-selector" name="guest[people]">
          <option value="1">1</option>
          <option id="twopeople" value="2">2</option>
        </select>
      </div>
    </div>
    <span
      style="
        font-size: 20px;
        font-family: Satisfy;
        font-style: italic;
        color: #c00;
      "
      >Tap the number to adjust</span
    >
    <div style="display: flex; justify-content: center">
      <input type="submit" id="submit" value="RSVP" name="commit" />
    </div>
    <% end %> <% if @guest.errors.any? %> <% @guest.errors.full_messages.each do
    |msg| %> <%= msg %> <% end %> <% end %>
  </body>
</html>
<script>
  const yesCheckbox = document.querySelector("#yescheckbox")
  const noCheckbox = document.querySelector("#nocheckbox")
  const realCheckbox = document.querySelector("#attending")

  function selectAttending(choice) {
    if (choice === "yes") {
      yesCheckbox.innerHTML = "X"
      noCheckbox.innerHTML = ""
      realCheckbox.checked = true
    } else {
      yesCheckbox.innerHTML = ""
      noCheckbox.innerHTML = "X"
      realCheckbox.checked = false
    }
  }

  const singles = ["george", "abel", "maria"]
  const input = document.querySelector("#nameinput")
  input.addEventListener("change", hideMultiGuest)

  function hideMultiGuest() {
    singles.forEach((single) => {
      if (String(input.value).toLowerCase().includes(single)) {
        document.querySelector("#twopeople").remove()
      }
    })
  }
</script>

app/views/guests/show.html.erb
<%# <p style="color: green"><%= notice %>
<%# </p> %>

<html>
<head>
<link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Satisfy&family=Send+Flowers&family=Bitter&display=swap"
      rel="stylesheet"
    />
<style>
body {
  background-color: #ecd;
        font-family: Send Flowers;
        text-align: center;
        margin: 0px;
}

a {
  border: 5px solid black;
        background-color: transparent;
        color: #000;
        font-family: Bitter;
        font-weight: 700;
        letter-spacing: 2px;
        margin-top: 25px;
        padding: 10px 30px;
        text-decoration: none;
        transition: background-color 0.3s ease-in, color 0.3s ease-in;
}

h1 {
  position: absolute;
  font-size: 100px !important;
  font-weight: 700;
  left: 50%;
  top: 40%;
  transform: translate(-50%,-50%);
  
}

#thankscontainer {
  /* height: 100vh;
  width: 100vw;
  display: "flex";
  flex-direction: "column";
  justify-content:"center";
  align-items:"center"; */
}
</style>
</head>
<body>

<%# <%= render @guest %> 

<div id="thankscontainer">
<h1>Thank you!</h1>
<%# <h2>
  <%= link_to "Update your RSVP", new_guest_path(@guest) %> 
  <%# </h2>  %>
  
</div>
</body>
</html>

app/views/guests/thanks.html.erb
<h1>THANK YOU!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stephen and Andrea</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>